/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_jobs__job_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Items */
        post: operations["accept_items_api_v1_jobs__job_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Job */
        get: operations["export_job_api_v1_jobs__job_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Item */
        patch: operations["correct_item_api_v1_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/items/{item_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Item */
        post: operations["accept_item_api_v1_items__item_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert Item */
        post: operations["revert_item_api_v1_items__item_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ktru/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Catalog */
        get: operations["search_catalog_api_v1_ktru_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ktru/{ktru_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_v1_ktru__ktru_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_job_api_v1_jobs_post */
        Body_create_job_api_v1_jobs_post: {
            /** File */
            file: string;
        };
        /**
         * BulkAccept
         * @example {
         *       "min_confidence": 85
         *     }
         */
        BulkAccept: {
            /**
             * Min Confidence
             * @description Принять все позиции с уверенностью не ниже
             */
            min_confidence: number;
        };
        /** BulkAcceptResult */
        BulkAcceptResult: {
            /** Accepted Count */
            accepted_count: number;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Ktru Code */
            ktru_code: string;
            /** Ktru Name */
            ktru_name?: string | null;
            /** Confidence */
            confidence: number;
        };
        /** Characteristic */
        Characteristic: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Unit */
            unit?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthComponent */
        HealthComponent: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Components */
            components: components["schemas"]["HealthComponent"][];
        };
        /** ItemAttributes */
        ItemAttributes: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Model */
            model?: string | null;
            /** Characteristics */
            characteristics?: components["schemas"]["Characteristic"][];
        };
        /** ItemCorrection */
        ItemCorrection: {
            /** Ktru Code */
            ktru_code: string;
            /** Ktru Name */
            ktru_name?: string | null;
        };
        /**
         * ItemOut
         * @example {
         *       "attributes": {
         *         "brand": "Dell",
         *         "characteristics": [
         *           {
         *             "name": "ОЗУ",
         *             "unit": "ГБ",
         *             "value": "16"
         *           }
         *         ],
         *         "model": "Latitude 5540",
         *         "name": "Ноутбук"
         *       },
         *       "candidates": [
         *         {
         *           "confidence": 94,
         *           "ktru_code": "26.20.11.110-00000009",
         *           "ktru_name": "Машины вычислительные портативные"
         *         }
         *       ],
         *       "confidence": 94,
         *       "id": "01aaa595-b008-4229-8a74-c3ac387f0261",
         *       "job_id": "c82cc353-9233-4ba2-8270-4f0139f37774",
         *       "ktru_code": "26.20.11.110-00000009",
         *       "ktru_name": "Машины вычислительные портативные",
         *       "method": "hybrid",
         *       "raw_columns": {
         *         "Наименование товара": "Ноутбук Dell",
         *         "№": "1"
         *       },
         *       "raw_name": "Ноутбук Dell Latitude 5540 16 ГБ",
         *       "row_number": 2,
         *       "status": "auto",
         *       "updated_at": "2026-10-05T15:41:27.812874Z"
         *     }
         */
        ItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Row Number */
            row_number: number;
            /** Raw Name */
            raw_name: string;
            /** Raw Columns */
            raw_columns: {
                [key: string]: unknown;
            };
            attributes?: components["schemas"]["ItemAttributes"] | null;
            /** Ktru Code */
            ktru_code: string | null;
            /** Ktru Name */
            ktru_name: string | null;
            /** Confidence */
            confidence: number | null;
            /** Method */
            method: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "auto" | "needs_review" | "accepted" | "corrected";
            /** Candidates */
            candidates?: components["schemas"]["CandidateOut"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ItemPage */
        ItemPage: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * JobCreated
         * @example {
         *       "filename": "spec.csv",
         *       "job_id": "c82cc353-9233-4ba2-8270-4f0139f37774",
         *       "status": "queued"
         *     }
         */
        JobCreated: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "failed";
            /** Filename */
            filename: string;
        };
        /**
         * JobOut
         * @example {
         *       "auto_count": 3,
         *       "corrected_count": 0,
         *       "created_at": "2026-10-05T15:41:27.454156Z",
         *       "failed_count": 0,
         *       "filename": "spec.csv",
         *       "finished_at": "2026-10-05T15:41:27.817763Z",
         *       "id": "c82cc353-9233-4ba2-8270-4f0139f37774",
         *       "needs_review_count": 1,
         *       "parse_seconds": 0.019,
         *       "processed_count": 4,
         *       "started_at": "2026-10-05T15:41:27.792843Z",
         *       "status": "done",
         *       "total_count": 4
         *     }
         */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "failed";
            /** Total Count */
            total_count: number;
            /** Processed Count */
            processed_count: number;
            /** Failed Count */
            failed_count: number;
            /**
             * Auto Count
             * @default 0
             */
            auto_count: number;
            /**
             * Needs Review Count
             * @default 0
             */
            needs_review_count: number;
            /**
             * Corrected Count
             * @default 0
             */
            corrected_count: number;
            /** Error */
            error: string | null;
            /** Parse Seconds */
            parse_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * KtruPositionOut
         * @example {
         *       "characteristics": [
         *         {
         *           "name": "масса",
         *           "unit": "кг",
         *           "value": "не более 10"
         *         }
         *       ],
         *       "ktru_code": "26.20.11.110-00000009",
         *       "ktru_name": "Машины вычислительные портативные",
         *       "okpd2_code": "26.20.11.110"
         *     }
         */
        KtruPositionOut: {
            /** Ktru Code */
            ktru_code: string;
            /** Ktru Name */
            ktru_name: string;
            /** Okpd2 Code */
            okpd2_code?: string | null;
            /** Characteristics */
            characteristics?: components["schemas"]["Characteristic"][];
        };
        /** KtruSearchPage */
        KtruSearchPage: {
            /** Items */
            items: components["schemas"]["KtruPositionOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_api_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_jobs__job_id__items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                q?: string | null;
                sort_by?: "row_number" | "confidence" | "updated_at";
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_items_api_v1_jobs__job_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkAcceptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_job_api_v1_jobs__job_id__export_get: {
        parameters: {
            query?: {
                format?: "csv" | "xlsx";
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_item_api_v1_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_item_api_v1_items__item_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_item_api_v1_items__item_id__revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_catalog_api_v1_ktru_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KtruSearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_ktru__ktru_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ktru_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KtruPositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
